# Generated by Django 5.2.3 on 2025-07-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_stock_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.IntegerField(null=True),
        ),
    ]
